"""
backend/app/analyzers/documentation/generator.py

Purpose
-------
Generate a project-level summary document after indexing (build plan §37
"Project Summary Memory" / §61 "Documentation Generation").

Responsibility
--------------
Assemble one Markdown document entirely from deterministic facts already in the
index — architecture (roles/layers), packages, key classes with their one-line
purposes, the SQL/dynamic-SQL picture, non-secret configuration, external
dependencies, and "known hotspots" (heavily-depended-on classes, unresolved
dynamic SQL, parse failures). Optionally prepends a short LLM-written purpose
paragraph synthesised *from those same facts* — never from guessing — and
degrades silently to a one-line heuristic purpose if no local model is available.

This is a read-only report generator: it never touches source code, only the
index. Re-running it after a re-index reflects the current state exactly.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

from backend.app.analyzers.architecture.extractor import Architecture, ArchitectureExtractor
from backend.app.models.database import get_connection

log = logging.getLogger("codexray.docgen")

_MAX_HOTSPOTS = 10
_MAX_KEY_CLASSES_PER_LAYER = 12


@dataclass
class ProjectDoc:
    project: str
    generated_at: str
    purpose: str
    purpose_source: str          # "llm" | "heuristic"
    counts: dict = field(default_factory=dict)
    architecture: Architecture | None = None
    packages: list[dict] = field(default_factory=list)
    key_classes: dict[str, list[dict]] = field(default_factory=dict)   # layer -> classes
    sql_summary: dict = field(default_factory=dict)
    dynamic_sql_summary: dict = field(default_factory=dict)
    config: list[dict] = field(default_factory=list)
    dependencies: list[dict] = field(default_factory=list)
    hotspots: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "project": self.project,
            "generated_at": self.generated_at,
            "purpose": self.purpose,
            "purpose_source": self.purpose_source,
            "counts": self.counts,
            "architecture": self.architecture.as_dict() if self.architecture else None,
            "packages": self.packages,
            "key_classes": self.key_classes,
            "sql_summary": self.sql_summary,
            "dynamic_sql_summary": self.dynamic_sql_summary,
            "config": self.config,
            "dependencies": self.dependencies,
            "hotspots": self.hotspots,
        }

    def to_markdown(self) -> str:
        c = self.counts
        lines = [
            f"# {self.project} — Project Summary",
            "",
            f"_Generated by CodeXray on {self.generated_at}. Every fact below comes from the "
            f"deterministic index (AST + SQL parser + dependency graph) — re-run after re-indexing "
            f"to refresh._",
            "",
            "## Purpose",
            "",
            self.purpose,
            "",
            "## At a glance",
            "",
            f"| files | classes | methods | SQL queries | dynamic SQL | tables |",
            f"|---|---|---|---|---|---|",
            f"| {c.get('files',0)} | {c.get('classes',0)} | {c.get('methods',0)} | "
            f"{c.get('sql_queries',0)} | {c.get('dynamic_sql',0)} | {c.get('tables',0)} |",
            "",
        ]

        if self.architecture:
            lines += ["## Architecture", ""]
            for layer, members in self.architecture.layers.items():
                lines.append(f"- **{layer}**: {', '.join(sorted(members)[:20])}"
                             + (" …" if len(members) > 20 else ""))
            lines.append("")
            lines.append(f"**Entry points:** {', '.join(self.architecture.entry_points) or '_none detected_'}")
            lines.append(f"**Data access:** {', '.join(self.architecture.data_access) or '_none detected_'}")
            if self.architecture.external_integrations:
                lines.append(f"**External integrations:** {', '.join(self.architecture.external_integrations)}")
            lines.append("")

        if self.packages:
            lines += ["## Modules / Packages", "", "| package | classes |", "|---|---|"]
            for p in self.packages:
                lines.append(f"| `{p['package']}` | {p['class_count']} |")
            lines.append("")

        if self.key_classes:
            lines += ["## Key classes", ""]
            for layer, classes in self.key_classes.items():
                lines.append(f"### {layer}")
                lines.append("")
                for cls in classes:
                    purpose = f" — {cls['purpose']}" if cls.get("purpose") else ""
                    lines.append(f"- **{cls['name']}** (`{cls['role']}`){purpose}")
                lines.append("")

        if self.sql_summary:
            s = self.sql_summary
            lines += [
                "## SQL architecture", "",
                f"- {s.get('total', 0)} SQL statements found "
                f"({s.get('select', 0)} SELECT, {s.get('write', 0)} write, {s.get('ddl', 0)} DDL)",
                f"- Tables touched: {', '.join(s.get('tables', [])[:25]) or '_none_'}"
                + (" …" if len(s.get("tables", [])) > 25 else ""),
                "",
            ]

        if self.dynamic_sql_summary:
            d = self.dynamic_sql_summary
            lines += [
                "## Dynamic SQL", "",
                f"- {d.get('total', 0)} dynamically-constructed SQL sites: "
                f"{d.get('RESOLVED', 0)} resolved, {d.get('PARTIALLY_RESOLVED', 0)} partially resolved, "
                f"{d.get('UNRESOLVED', 0)} unresolved",
                f"- Metadata-registry tables driving dynamic SQL: "
                f"{', '.join(d.get('metadata_tables', [])) or '_none_'}",
                "",
            ]

        if self.dependencies:
            lines += ["## External dependencies", "", "| library | imports |", "|---|---|"]
            for d in self.dependencies[:20]:
                lines.append(f"| `{d['name']}` | {d['count']} |")
            lines.append("")

        if self.config:
            lines += ["## Configuration", ""]
            for entry in self.config[:40]:
                lines.append(f"- `{entry['key']}` = {entry['value']}  _({entry['file']})_")
            lines.append("")

        if self.hotspots:
            lines += ["## Known hotspots", ""]
            lines += [f"- {h}" for h in self.hotspots]
            lines.append("")

        return "\n".join(lines)


class ProjectDocGenerator:
    def __init__(self, project_id: int, conn=None) -> None:
        self.pid = project_id
        self.conn = conn or get_connection()

    # ------------------------------------------------------------------ build
    def generate(self, *, use_llm: bool = False) -> ProjectDoc:
        c = self.conn
        proj = c.execute("SELECT name FROM projects WHERE id=?", (self.pid,)).fetchone()
        name = proj["name"] if proj else str(self.pid)

        counts = self._counts()
        arch = ArchitectureExtractor(c).extract(self.pid)
        packages = self._packages()
        key_classes = self._key_classes(arch)
        sql_summary = self._sql_summary()
        dyn_summary = self._dynamic_sql_summary()
        config = self._config()
        deps = self._dependencies()
        hotspots = self._hotspots(dyn_summary)

        purpose, source = self._purpose(name, arch, sql_summary, use_llm=use_llm)

        return ProjectDoc(
            project=name,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            purpose=purpose,
            purpose_source=source,
            counts=counts,
            architecture=arch,
            packages=packages,
            key_classes=key_classes,
            sql_summary=sql_summary,
            dynamic_sql_summary=dyn_summary,
            config=config,
            dependencies=deps,
            hotspots=hotspots,
        )

    # --------------------------------------------------------------- sections
    def _counts(self) -> dict:
        c = self.conn

        def n(table: str) -> int:
            return c.execute(f"SELECT COUNT(*) FROM {table} WHERE project_id=?", (self.pid,)).fetchone()[0]

        tables = c.execute(
            "SELECT COUNT(DISTINCT t.name) FROM sql_tables t JOIN sql_queries q ON q.id=t.query_id "
            "WHERE q.project_id=?", (self.pid,)
        ).fetchone()[0]
        return {
            "files": n("files"), "classes": n("classes"), "methods": n("methods"),
            "sql_queries": n("sql_queries"), "dynamic_sql": n("dynamic_sql"), "tables": tables,
        }

    def _packages(self) -> list[dict]:
        rows = self.conn.execute(
            "SELECT package, COUNT(*) AS n FROM classes WHERE project_id=? AND package IS NOT NULL "
            "GROUP BY package ORDER BY n DESC", (self.pid,)
        ).fetchall()
        return [{"package": r["package"], "class_count": r["n"]} for r in rows]

    def _key_classes(self, arch: Architecture) -> dict[str, list[dict]]:
        summaries = {
            r["qualified"]: r["summary"] for r in self.conn.execute(
                "SELECT qualified, summary FROM method_summaries WHERE project_id=?", (self.pid,))
        }
        by_layer: dict[str, list[dict]] = {}
        for comp in arch.components:
            # a light class-level purpose: the first non-constructor method's summary
            purpose = None
            for q, s in summaries.items():
                cls, _, method = q.rpartition(".")
                if cls == comp.name and method != comp.name:   # skip the constructor
                    purpose = s
                    break
            by_layer.setdefault(comp.layer, []).append(
                {"name": comp.name, "role": comp.role, "purpose": purpose}
            )
        # keep it readable: cap per layer, prefer classes with a purpose
        for layer, classes in by_layer.items():
            classes.sort(key=lambda x: x["purpose"] is None)
            by_layer[layer] = classes[:_MAX_KEY_CLASSES_PER_LAYER]
        return by_layer

    def _sql_summary(self) -> dict:
        rows = self.conn.execute(
            "SELECT query_type, COUNT(*) AS n FROM sql_queries WHERE project_id=? GROUP BY query_type",
            (self.pid,),
        ).fetchall()
        by_type = {r["query_type"]: r["n"] for r in rows}
        tables = [r["name"] for r in self.conn.execute(
            "SELECT DISTINCT t.name FROM sql_tables t JOIN sql_queries q ON q.id=t.query_id "
            "WHERE q.project_id=? ORDER BY t.name", (self.pid,))]
        return {
            "total": sum(by_type.values()),
            "select": by_type.get("SELECT", 0),
            "write": sum(by_type.get(k, 0) for k in ("INSERT", "UPDATE", "DELETE", "MERGE")),
            "ddl": by_type.get("DDL", 0),
            "tables": tables,
        }

    def _dynamic_sql_summary(self) -> dict:
        rows = self.conn.execute(
            "SELECT resolution_status, COUNT(*) AS n FROM dynamic_sql WHERE project_id=? "
            "GROUP BY resolution_status", (self.pid,)
        ).fetchall()
        out = {r["resolution_status"]: r["n"] for r in rows}
        out["total"] = sum(out.values())
        meta_tables = set()
        for d in self.conn.execute("SELECT id FROM dynamic_sql WHERE project_id=?", (self.pid,)):
            for dep in self.conn.execute(
                "SELECT evidence_json FROM dynamic_sql_dependencies WHERE dynamic_sql_id=? "
                "AND dependency_type='METADATA_QUERY'", (d["id"],)
            ):
                import json
                for e in json.loads(dep["evidence_json"] or "[]"):
                    meta_tables.update(e.get("metadata_tables", []))
        out["metadata_tables"] = sorted(meta_tables)
        return out

    def _config(self) -> list[dict]:
        rows = self.conn.execute(
            "SELECT ce.key, ce.value, ce.is_secret, f.path FROM config_entries ce "
            "JOIN files f ON f.id=ce.file_id WHERE ce.project_id=? ORDER BY ce.key", (self.pid,)
        ).fetchall()
        return [{"key": r["key"], "value": "***" if r["is_secret"] else r["value"], "file": r["path"]}
                for r in rows]

    def _dependencies(self) -> list[dict]:
        project_packages = {r["package"] for r in self.conn.execute(
            "SELECT DISTINCT package FROM classes WHERE project_id=? AND package IS NOT NULL", (self.pid,))}
        rows = self.conn.execute(
            "SELECT imported FROM imports WHERE project_id=? AND is_wildcard=0", (self.pid,)
        ).fetchall()
        counts: dict[str, int] = {}
        for r in rows:
            imp = r["imported"]
            if any(imp.startswith(p) for p in project_packages):
                continue
            parts = imp.split(".")
            top = ".".join(parts[:2]) if len(parts) > 1 else imp
            counts[top] = counts.get(top, 0) + 1
        return sorted(({"name": k, "count": v} for k, v in counts.items()), key=lambda d: -d["count"])

    def _hotspots(self, dyn_summary: dict) -> list[str]:
        out: list[str] = []
        # most-depended-on METHODS DEFINED IN THIS PROJECT (fan-in) — JDBC/stdlib
        # calls (bare names like `executeQuery`) are excluded, same as the graph export.
        known_methods = {
            f'{r["cn"]}.{r["mn"]}' for r in self.conn.execute(
                "SELECT c.name AS cn, m.name AS mn FROM methods m LEFT JOIN classes c ON c.id=m.class_id "
                "WHERE m.project_id=?", (self.pid,))
        }
        rows = self.conn.execute(
            "SELECT dst_label, COUNT(*) AS n FROM dependencies WHERE project_id=? AND dst_kind='method' "
            "GROUP BY dst_label ORDER BY n DESC", (self.pid,),
        ).fetchall()
        shown = 0
        for r in rows:
            if r["dst_label"] not in known_methods:
                continue
            if r["n"] >= 3:
                out.append(f"`{r['dst_label']}` is called from {r['n']} places — check impact before changing it")
                shown += 1
            if shown >= 5:
                break

        if dyn_summary.get("UNRESOLVED"):
            out.append(f"{dyn_summary['UNRESOLVED']} dynamic SQL site(s) are fully UNRESOLVED — "
                       "runtime evidence needed to determine the query")
        if dyn_summary.get("PARTIALLY_RESOLVED"):
            out.append(f"{dyn_summary['PARTIALLY_RESOLVED']} dynamic SQL site(s) depend on metadata lookups — "
                       "the physical table/columns are not fixed at compile time")

        failed = self.conn.execute(
            "SELECT COUNT(*) FROM parse_failures WHERE project_id=?", (self.pid,)).fetchone()[0]
        if failed:
            out.append(f"{failed} file(s) failed to parse and are missing from this index — see Overview")
        return out

    def _purpose(self, name: str, arch: Architecture, sql: dict, *, use_llm: bool) -> tuple[str, str]:
        entry = ", ".join(arch.entry_points[:3]) or "no clear entry point detected"
        heuristic = (
            f"{name} is a Java{'/' if sql.get('total') else ''}"
            f"{'SQL' if sql.get('total') else ''} application with {len(arch.components)} classes "
            f"across {len(arch.layers)} layers ({', '.join(arch.layers)}). "
            f"Entry point(s): {entry}. It executes {sql.get('total', 0)} SQL statements against "
            f"{len(sql.get('tables', []))} tables."
        )
        if not use_llm:
            return heuristic, "heuristic"

        try:
            from backend.app.config.settings import get_settings
            from backend.app.llm.provider import LLMUnavailable, get_provider
            provider = get_provider(get_settings().llm)
            facts = (
                f"Project: {name}\nLayers: {arch.layers}\nEntry points: {arch.entry_points}\n"
                f"Data access classes: {arch.data_access}\nSQL: {sql.get('total',0)} statements, "
                f"tables: {sql.get('tables', [])[:20]}"
            )
            resp = provider.generate(
                "You write a single tight paragraph (3-5 sentences) describing what a Java project "
                "does, for a project-summary document. Use ONLY the facts given. No headers, no lists, "
                "no markdown, plain prose. Do not invent business purpose beyond what the facts support.",
                f"Facts:\n{facts}\n\nWrite the paragraph.",
                temperature=0.1, max_tokens=220,
            )
            text = resp.text.strip()
            return (text if text else heuristic), ("llm" if text else "heuristic")
        except Exception as exc:  # LLMUnavailable or anything else — never fail doc generation
            log.info("LLM purpose paragraph skipped: %s", exc)
            return heuristic, "heuristic"
